# Generated by Django 5.0.3 on 2024-04-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_appli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyager',
            name='valide',
            field=models.BooleanField(default=0),
        ),
    ]
